<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Run all test cases</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>8fd26ec6-ed09-4e5a-bcbb-3a63530359ed</testSuiteGuid>
   <testCaseLink>
      <guid>fa27b014-5f2b-453c-b690-7c9788a2cc2f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Driven Test Cases/User Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>78965324-8e1c-486d-9273-1c7f5b654c86</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/User Accounts</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>78965324-8e1c-486d-9273-1c7f5b654c86</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>unameOrEmail</value>
         <variableId>7805109e-614c-496a-a30d-a79ecc85fbc1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>78965324-8e1c-486d-9273-1c7f5b654c86</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>08c7b652-5af2-4eaf-98bc-e295fce2172d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a3d60e6-1c51-4eba-8f39-51e35ed479ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Driven Test Cases/Create Public Chanels</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>fda261d6-1b47-4471-a51a-fe1c200a03d1</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Public Chanels</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>fda261d6-1b47-4471-a51a-fe1c200a03d1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>isPublic</value>
         <variableId>0f086a8d-71a0-497e-b991-3bd5b62dfefd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fda261d6-1b47-4471-a51a-fe1c200a03d1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>name</value>
         <variableId>685a9311-0453-4b35-b145-33e491d29f82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fda261d6-1b47-4471-a51a-fe1c200a03d1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>purpose</value>
         <variableId>a3a35dfe-73f2-40de-87b5-cafafbf0809c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fda261d6-1b47-4471-a51a-fe1c200a03d1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>header</value>
         <variableId>99c940de-e35d-4358-8c99-d29198e3f175</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>914ba0f5-52c8-45c8-9c3c-35d8aff97dd7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/View Team Members</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>88e08026-a47c-450e-b3e5-230b5958e3f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Leave Team</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>50f8cd32-8774-4eed-a586-b3b1be4bf40f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Team Name</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1553dfa9-3237-424f-80b8-95e1160d9198</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Switch Online Status</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0fdf2015-15ef-4334-a08c-cf611e904ff1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Remove Message Reactions</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>5d399981-47fa-47a4-8ba4-713e7a49df62</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mark Unread Messages</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>009adc01-b58f-4a91-84a8-75359f46f7f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/View Access History</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>383c7d41-2ffc-42cb-94dc-829b00b581e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Add Direct Messages</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b0cb4c71-f1db-44b3-8f81-2f7e1bc66b14</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Show Help</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>5545f440-ed30-49a9-8fab-c45e26feaf25</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Download App</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7311d50b-bb73-4be3-bddc-a1d3d7ee0398</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Show About</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>00451448-f64b-46ff-8941-c5d60113569d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Logout</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>48e97461-ffaf-4170-aace-7f3b1d0e0417</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Send Messages</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3a8798dc-d6c7-4dcc-b4c9-5f00f74e62f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Show Keyboard Shortcuts</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>745a6ef6-da30-498f-9e42-f076ebbff4e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/View Chanels Info</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>5e59d82e-f1f9-4bc0-8e93-2b2d2cdceab6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Send Files</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>fa02847d-6061-43c7-812e-91d77166d33f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Switch Chanels</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>20654ca9-a8cf-4ee1-bb36-4cc27c525198</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/View Chanel Members</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8b0c6cc3-26f0-41d7-8b32-0f457135e2eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Remove Direct Messages</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1b081023-26b8-4f97-8226-9afc8b516f08</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Switch Chanels</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>32e2ca97-09b3-465f-bfed-f35434d6d66a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Reply Messages</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e6cb8881-26d9-46b3-9517-558256b620e2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pin Messages</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>766b4ac0-55f9-4cfa-9be8-d6a24dcc84da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Show Recent Mentions</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>45bf5861-7f07-4633-9a4b-87757af3ac10</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Report A Problem</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4c4495db-6eb2-4fe9-a4ce-1a61fbc8a850</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Add Flags</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0d3ca481-488d-4c33-b831-385969d9a3ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Add Message Reactions</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>793c346a-293c-4167-b42f-7ba1d8c36c17</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Delete Message</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>355f8f9d-f820-4e09-973a-cb9f52ab9c85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Messages</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a6d2fe02-6a26-4cfa-be0c-6bd80852d230</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Ediit Account Email</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2adfa373-9fa7-4fb3-8642-9dd780fef578</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36f68d09-48ba-4837-8dad-15217c7b6905</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>305c88cd-e665-4e36-b396-9b0c1258ea95</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0bc02054-c9da-484d-8d13-38fb53db6e9a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Driven Test Cases/Add Incoming Webhook</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a6fbe2c-150f-4946-aa72-4f1781751ff4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>594c71c1-d6a1-4ccf-8513-1e662d76c811</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43e42a92-7b95-44c8-8227-947842021b24</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6a474e42-ae3f-48c8-a2dc-7de9111ef98f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Driven Test Cases/Add Outgoing Webhook</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b81c936-817e-4ed9-bf38-6487aa525806</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2530cf10-0f03-463d-a514-886b1847cb2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8893dcb7-51a4-4561-bcb8-745c82f775aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb6c4d04-d3b5-48a0-9dc7-f84f6f64c0fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62e9c9ab-dcbc-41bc-af92-317e0113dd86</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>25f6e6f5-a047-4e8c-ae39-80a91e5b94a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Driven Test Cases/Add Slash Commands</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d02f76af-9da7-4d29-8e34-0d5456136afb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c0137c7-9571-42e0-a336-892cd28f4bdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de93b260-637d-44f6-8e48-ff010ab5b446</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cc2da73-c160-455b-84a8-3ff1fee7fb73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1ef8fbf-dd4c-46a5-9f02-535d20ef8935</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>426d7ff0-52ff-4e75-bed5-2995d2bca317</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f58b0996-5201-4d17-9685-05dcb22dc6a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63c82b48-9212-4a2e-aae7-5ea23263fac5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>96ea66cb-d977-440f-ad6a-964c8ab29e1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Driven Test Cases/Add Team Members</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fca8139d-4bd1-45c0-9533-8f5991134969</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>accc6203-c808-432c-8cb1-43ea57491428</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Driven Test Cases/Create New Team</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfa34ddb-dcfd-42da-a957-3a3b955fd635</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97ff7a41-f1c8-4042-bee4-fe30746699f6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b068e5b6-b707-4319-a41e-2be9aec5b28d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Driven Test Cases/Edit Account FullName</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86db670b-ad8a-4b24-ab6b-edc9e4e81dfe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df0910df-efdc-4b71-8e93-3c34074a3997</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4c6c4da-91cf-465b-8a5e-39499243aaf5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Driven Test Cases/Edit Account Nickname</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d443cbb-729d-409d-b1a0-e5723dda775c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c71977c2-50b2-448a-8f9d-10fec04b0d02</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Driven Test Cases/Edit Account Position</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>743c4492-22b5-4df3-84f3-0ec09cc4ed4e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>85e318c1-661f-4a52-a7f3-7a38d8fe88f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Driven Test Cases/Edit Account Username</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48206e72-5a29-4c44-a874-e70b83b9d66e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
